
CREATE DATABASE DB_AAMM_DEV;
CREATE DATABASE DB_AAMM_STAGING;
CREATE DATABASE DB_AAMM;

CREATE USER 'web_aamm_le'@'%' IDENTIFIED BY '1234';
GRANT SELECT ON DB_AAMM.* TO 'web_aamm_le'@'%';
FLUSH PRIVILEGES;

CREATE USER 'web_aamm_ed'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON DB_AAMM.* TO 'web_aamm_ed'@'%';
FLUSH PRIVILEGES;
