update ta_etiquetas set etiqueta='Kimura de pie' where etiqueta='Quimura de pie';
update ta_etiquetas set etiqueta='Kimura' where etiqueta='Quimura';

UPDATE ta_etiquetas SET categoria_1='Disciplina General', categoria_2='', notas='Disciplina General', orden=10 where idetiqueta=6;
UPDATE ta_etiquetas SET categoria_1='Disciplina General', categoria_2='', notas='Disciplina General', orden=20 where idetiqueta=7;
UPDATE ta_etiquetas SET categoria_1='video', categoria_2='', notas='Filtro de sistema', orden=30 where idetiqueta=54;
UPDATE ta_etiquetas SET categoria_1='VARIOS', categoria_2='', notas='Filtro de contexto', orden=40 where idetiqueta=82;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='montada', notas='Posición dominante', orden=50 where idetiqueta=9;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='montada', notas='Variante de montada', orden=60 where idetiqueta=48;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='montada', notas='Control posicional (Knee on belly)', orden=70 where idetiqueta=33;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='montada', notas='Pase / Control hacia montada', orden=80 where idetiqueta=24;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='100kg', notas='Control lateral', orden=90 where idetiqueta=10;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='100kg', notas='Unificado "100Kg" a "100kg"', orden=100 where idetiqueta=79;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='100kg', notas='Sistema de control de brazos', orden=110 where idetiqueta=80;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='norte sur', notas='Control posicional', orden=120 where idetiqueta=11;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='espalda', notas='Control posicional', orden=130 where idetiqueta=8;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='cuatro apoyos', notas='Posición de tortuga', orden=140 where idetiqueta=47;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='cuatro apoyos', notas='Traccionar a la tortuga (Transición)', orden=150 where idetiqueta=53;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='', notas='Control de hombros previos a llave/estrangulación', orden=160 where idetiqueta=64;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=170 where idetiqueta=13;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=180 where idetiqueta=75;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=190 where idetiqueta=46;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=200 where idetiqueta=45;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=210 where idetiqueta=61;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=220 where idetiqueta=74;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='de pie', notas='Guardia abierta / Transición a derribo', orden=230 where idetiqueta=37;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=240 where idetiqueta=88;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=250 where idetiqueta=12;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=260 where idetiqueta=49;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=270 where idetiqueta=58;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='guardia', notas='Familia de Guardias', orden=280 where idetiqueta=59;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='', notas='Guardia simétrica enfocada a llaves de pie', orden=290 where idetiqueta=51;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='piernas', notas='Control posicional', orden=300 where idetiqueta=85;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='', notas='Fase de combate en pie', orden=310 where idetiqueta=34;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='de pie', notas='Trabajo de agarres arriba', orden=320 where idetiqueta=35;
UPDATE ta_etiquetas SET categoria_1='posición', categoria_2='', notas='Trabajo de agarres arriba', orden=330 where idetiqueta=44;
UPDATE ta_etiquetas SET categoria_1='derribo', categoria_2='derribo', notas='Concepto general', orden=340 where idetiqueta=25;
UPDATE ta_etiquetas SET categoria_1='derribo', categoria_2='derribo', notas='Técnica de derribo', orden=350 where idetiqueta=56;
UPDATE ta_etiquetas SET categoria_1='derribo', categoria_2='derribo', notas='Técnica de derribo', orden=360 where idetiqueta=57;
UPDATE ta_etiquetas SET categoria_1='derribo', categoria_2='derribo', notas='Técnica de derribo', orden=370 where idetiqueta=63;
UPDATE ta_etiquetas SET categoria_1='derribo', categoria_2='derribo', notas='Control de brazo de pie para derribar', orden=380 where idetiqueta=84;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Inversiones desde el suelo', orden=390 where idetiqueta=18;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Repeticiones de agilidad', orden=400 where idetiqueta=27;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Pasar la guardia (acción)', orden=410 where idetiqueta=38;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Escape', orden=420 where idetiqueta=41;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Escape genérico', orden=430 where idetiqueta=42;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Contraataques / Reacciones', orden=440 where idetiqueta=43;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Inversión avanzada avanzada', orden=450 where idetiqueta=65;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Trabajo de pase de guardia', orden=460 where idetiqueta=81;
UPDATE ta_etiquetas SET categoria_1='movimentación', categoria_2='', notas='Concepto defensivo general', orden=470 where idetiqueta=83;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='', notas='Concepto raíz de sumisión', orden=480 where idetiqueta=14;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque de cuello', orden=490 where idetiqueta=22;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque de cuello/brazo', orden=500 where idetiqueta=15;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque desde control lateral', orden=510 where idetiqueta=78;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque de cuello', orden=520 where idetiqueta=21;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque de cuello', orden=530 where idetiqueta=40;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque de cuello', orden=540 where idetiqueta=52;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Sumisión espinal (cuello)', orden=550 where idetiqueta=55;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque de cuello por la espalda', orden=560 where idetiqueta=62;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Control/Presión cervical', orden=570 where idetiqueta=72;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Ataque de cuello', orden=580 where idetiqueta=73;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='estrangulación', notas='Transición a estrangulación (Darce/Anaconda)', orden=590 where idetiqueta=77;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='brazo', notas='Familia de ataques de articulación', orden=600 where idetiqueta=16;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='brazo', notas='Ataque de hombro con piernas', orden=610 where idetiqueta=17;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='brazo', notas='Ataque de brazo', orden=620 where idetiqueta=19;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='brazo', notas='Ataque de hombro', orden=630 where idetiqueta=20;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='brazo', notas='Luxación por compresión', orden=640 where idetiqueta=28;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='brazo', notas='Luxación de muñeca', orden=650 where idetiqueta=36;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='brazo', notas='Llave de brazo recta alternativa', orden=660 where idetiqueta=60;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='dolor', notas='Sumisiones por presión/dolor', orden=670 where idetiqueta=23;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='pie', notas='Familia de ataques de pierna (Straight Foot Lock)', orden=680 where idetiqueta=29;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='pie', notas='Variante de ataque de pierna', orden=690 where idetiqueta=30;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='pie', notas='Ataque rotacional de tobillo (Toe hold)', orden=700 where idetiqueta=31;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='pie', notas='Ataque de pie', orden=710 where idetiqueta=32;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='pie', notas='Luxación por compresión (Calf slicer)', orden=720 where idetiqueta=39;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='pie', notas='Llave de talón', orden=740 where idetiqueta=50;
UPDATE ta_etiquetas SET categoria_1='finalización', categoria_2='pie', notas='Luxación recta de rodilla (Knee bar)', orden=750 where idetiqueta=76;
UPDATE ta_etiquetas SET categoria_1='VARIOS', categoria_2='', notas='Filtro general / Varios', orden=760 where idetiqueta=26;
UPDATE ta_etiquetas SET categoria_1='VARIOS', categoria_2='', notas='Concepto transversal', orden=770 where idetiqueta=87;